# Identifiants SonarCloud (Indispensables)
sonar.projectKey=richinelle_Projet_fil_rouge
sonar.organization=richinelle
sonar.host.url=https://sonarcloud.io

# Configuration des sources
sonar.sources=app,routes,database
sonar.tests=tests
sonar.language=php
sonar.sourceEncoding=UTF-8

# Rapports de tests (PHPUnit)
sonar.php.coverage.reportPaths=coverage.xml
#sonar.php.tests.reportPath=test-results.xml

# Exclusions
sonar.exclusions=docker/**
