sonar.projectKey=richinelle_Projet_fil_rouge_backend
sonar.organization=richinelle
sonar.sources=app
sonar.tests=tests
sonar.php.coverage.reportPaths=coverage.xml
sonar.exclusions=**/vendor/**,**/storage/**,**/bootstrap/**

