input {
  file {
    path => "/var/www/storage/logs/laravel.log"
    start_position => "beginning"
    type => "laravel"
  }
}

filter {
  if [type] == "laravel" {
    grok {
      match => {
        "message" => "\[%{TIMESTAMP_ISO8601:timestamp}\] %{WORD:env}\.%{WORD:level}: %{GREEDYDATA:message}"
      }
    }
  }
}

output {
  elasticsearch {
    hosts => ["elasticsearch:9200"]
    index => "laravel-logs-%{+YYYY.MM.dd}"
  }
}