name: CI/CD Backend SGEE

on:
  push:
    branches: [main]

jobs:
  sonarqube:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'
          coverage: xdebug

      - name: Installer dépendances Laravel
        working-directory: ./Backend
        run: composer install --no-interaction --ignore-platform-reqs

      - name: Préparer environnement Laravel
        working-directory: ./Backend
        run: |
          cp .env.example .env
          php artisan key:generate --force
          php artisan jwt:secret --force


      - name: Lancer les tests
        working-directory: ./Backend
        run: php artisan test --coverage-clover=coverage.xml

      - name: Analyse SonarCloud
        uses: SonarSource/sonarcloud-github-action@master
        with:
          projectBaseDir: ./Backend
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  deploy:
    runs-on: ubuntu-latest
    needs: sonarqube
    steps:
      - uses: actions/checkout@v4

      - name: Installer dépendances Laravel (sans dev)
        working-directory: ./Backend
        run: composer install --no-interaction --no-dev --optimize-autoloader --ignore-platform-reqs

      - name: Deploy Laravel via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USER }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./Backend/
          server-dir: /nguetsop.cdwfs.net/backend/
          exclude: |
            **/.git*
            **/.env
            **/docker-compose*
            **/docker/**
            **/Dockerfile
            **/node_modules/**
            **/.github/**
            **/.gitignore
